{
 "title": "Event Streams (Performance)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages in",
   "type": "timeseries",
   "description": "A count of the number of messages per second that the cluster is receiving. \n\nThis is a good summary of the level of traffic that the cluster is handling.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce requests",
   "type": "timeseries",
   "description": "A count of the produce requests per second that the cluster is receiving. \n\nEfficient applications will use batching to produce multiple messages in a single request, so this may be lower than the number of messages per second.\n\nThis is a good summary of the level of traffic that the cluster is handling.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Topic partitions under minimum-in-sync replicas",
   "type": "timeseries",
   "description": "This is a count of the number of topic partitions with a number of in-sync replicas which is under their minimum in sync replica configuration. \n\nProducer applications cannot produce to these partitions, and will be blocked until this is corrected. \n\nThe number of partitions in this state should be zero.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underminisrpartitioncount_value{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas per broker",
   "type": "timeseries",
   "description": "In a healthy cluster, each of the Kafka brokers should handle a roughly equal proportion of the work for the cluster. \n\nOne indicator of this is the number of topic partition replicas held on each broker. \n\nIt can never be exactly identical across all brokers, however having one broker responsible for a disproportionately high level of topic partition replicas should be avoided.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod) (kafka_server_replicamanager_partitioncount_value{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Brokers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Messages in",
   "type": "timeseries",
   "description": "In a healthy cluster, each of the Kafka brokers should handle a roughly equal proportion of the work for the cluster. \n\nOne indicator of this is the number of messages per second received by each broker. \n\nIt can never be exactly identical across all brokers, however having one broker responsible for a disproportionately high level of messages for the cluster should be avoided.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\", pod=\"my-kafka-cluster-kafka-3\"}[1m]))",
     "legendFormat": "Broker 0"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\", pod=\"my-kafka-cluster-kafka-4\"}[1m]))",
     "legendFormat": "Broker 1"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\", pod=\"my-kafka-cluster-kafka-5\"}[1m]))",
     "legendFormat": "Broker 2"
    }
   ]
  },
  {
   "title": "Bytes in",
   "type": "timeseries",
   "description": "In a healthy cluster, each of the Kafka brokers should handle a roughly equal proportion of the work for the cluster. \n\nOne indicator of this is the amount of data per second received by each broker. \n\nIt can never be exactly identical across all brokers, however having one broker responsible for a disproportionately high level of data for the cluster should be avoided.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\", pod=\"my-kafka-cluster-kafka-3\"}[1m]))",
     "legendFormat": "Broker 0"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\", pod=\"my-kafka-cluster-kafka-4\"}[1m]))",
     "legendFormat": "Broker 1"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\", pod=\"my-kafka-cluster-kafka-5\"}[1m]))",
     "legendFormat": "Broker 2"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Garbage Collection (secs per min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(jvm_gc_collection_seconds_count{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", container=\"kafka\", namespace=\"event-automation\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (jvm_memory_used_bytes{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\", area=\"heap\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU (Kafka)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_user_seconds_total{namespace=\"event-automation\", pod=~\"my-kafka-cluster-kafka-3|my-kafka-cluster-kafka-4|my-kafka-cluster-kafka-5\", container=\"kafka\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory (Kafka)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"event-automation\", pod=~\"my-kafka-cluster-kafka-4|my-kafka-cluster-kafka-5|my-kafka-cluster-kafka-3\", container=\"kafka\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Log flush rate",
   "type": "timeseries",
   "description": "Log flush rate is the rate at which log data is written to disk, in milliseconds.\n\nIt is a measure of the time taken to flush messages from in-memory log buffers to physical disks. Higher latency will slow down the request times for producer applications, and potentially lead to data loss in the event of a crash before a flush has completed.\n\nThis visualisation is showing the value for the 99th percentile - so 99% of the log latency measured is under the value displayed here. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(pod) (kafka_log_logflushstats_logflushrateandtimems{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\", quantile=\"0.99\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request handler pool - idle time",
   "type": "timeseries",
   "description": "This is a measure of the amount of time the request handler threads in the Kafka broker are spending idle. \n\nIt is an indicator of how busy the broker is when processing requests from client applications and other brokers.\n\nA high value indicates the request threads are mostly idle, and that the broker is under a low workload.\n\nA low value indicates the request handlers are fully utilized and potentially struggling to keep up with a high workload.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(pod) (kafka_server_kafkarequesthandlerpool_requesthandleravgidle_percent{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Bytes in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"event-automation\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}